# Generated by Django 4.2.13 on 2024-07-18 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetseeker', '0002_reservation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_of_visit',
            field=models.TimeField(default=datetime.datetime(2024, 7, 18, 15, 55, 17, 612066, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
