# Generated by Django 4.2.13 on 2024-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetseeker', '0003_reservation_time_of_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
