# Generated by Django 4.2.13 on 2024-07-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetseeker', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='places'),
        ),
    ]
